'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace WebFinalpart1

    Partial Public Class Transactionbse161001Entities1
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Transactionbse161001Entities1")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Property Transactionbse161001() As DbSet(Of Transactionbse161001)
    
    End Class

End Namespace
