'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebFinalpart1

    Partial Public Class Transactionbse161001
        Public Property TransactionId As Integer
        Public Property TransactionDate As Nullable(Of Date)
        Public Property TransactionType As String
        Public Property TransactionAmount As String
    
    End Class

End Namespace
